spring.application.name=store

# Dynamic DB connection: Uses Render env variables if present, otherwise falls back to your Aiven DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:connector}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Safe deployment rule: 'update' locally for quick dev, but 'validate' on Render to protect prod data
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Logging preferences
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dynamic Port: Fallback to 8080 locally; Render will automatically override this with its own port
server.port=${PORT:8080}